Feature/me 13 create share resp schema
ong-bitcoin-argentina/DIDI-SSI-VC-Validator pull request #26
Opened 2022-05-10 17:24 UTC by DoloresGarciaE

2022-05-30 19:40 UTC, claudio-uslenghi requested changes
Hay comentarios sin resolver

2022-05-31 22:02 UTC, MatiasOS requested changes

2022-05-31 22:02 UTC, MatiasOS commented on src/constants.ts
> +module.exports = { schemasMap };
usá porfa schemasByName

2022-06-02 15:38 UTC, claudio-uslenghi approved these changes

2022-06-02 15:38 UTC, merged